In [1]:
import os

import pandas as pd
from IPython.display import display

# INPUT_PATH = 'car-price-prediction/data/carsWithImages.csv'
# OUTPUT_PATH = 'car-price-prediction/data/carsWithImageCleaned.csv'
INPUT_PATH = os.path.join("..", "data", "carsWithImages.csv")
OUTPUT_PATH = os.path.join("..", "data", "carsWithImageCleaned.csv")

df = pd.read_csv(INPUT_PATH, index_col=0)

In [2]:
df.head()

,Url,Autovit Id,Pret,Oferit de,Categorie,Marca,Model,Versiune,Anul,Km,...,Capacitate baterie,Tuning,Predare leasing,Plata initiala (la predare),Valoare rata lunara,Numar de rate lunare ramase,Valoare reziduala,Contract baterie,Volan pe dreapta,Masina de epoca
0,https://www.autovit.ro/anunt/suzuki-vitara-1-6...,7049990250,16 999 EUR,Proprietar,Autoturisme,Suzuki,Vitara,1.6,2018,26 000 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autovit.ro/anunt/toyota-auris-1-8-...,7049960669,12 500 EUR,Proprietar,Autoturisme,Toyota,Auris,1.8 VVT-i Hybrid Automatik Touring Sports,2015,239 465 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autovit.ro/anunt/skoda-octavia-1-6...,7049895868,14 994 EUR,Firma,Autoturisme,Skoda,Octavia,1.6 TDI,2020,100 000 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autovit.ro/anunt/ford-focus-1-6-td...,7049990021,5 000 EUR,Proprietar,Autoturisme,Ford,Focus,1.6 TDCi DPF,2012,245 000 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autovit.ro/anunt/opel-insignia-ID7...,7049990234,17 800 EUR,Proprietar,Autoturisme,Opel,Insignia,NaN,2017,65 000 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# remove electric cars

df = df[df['Combustibil'] != 'Electric']

In [4]:
# see unique values in column Combustibil

df.Combustibil.unique()

array(['Benzina', 'Hibrid', 'Diesel', 'Benzina + CNG', 'Benzina + GPL'],
      dtype=object)

In [5]:
# delete Benzina + CNG and Benzina + GPL

df = df[df['Combustibil'] != 'Benzina + CNG']
df = df[df['Combustibil'] != 'Benzina + GPL']

In [6]:
# see unique values in column Transmisie

df.Transmisie.unique()

array([nan, 'Fata', '4x4 (automat)', '4x4 (manual)', 'Spate'],
      dtype=object)

In [7]:
# replace 4x4 (automat) and 4x4 (manual) with 4x4

df['Transmisie'] = df['Transmisie'].replace(['4x4 (automat)'], '4x4')
df['Transmisie'] = df['Transmisie'].replace(['4x4 (manual)'], '4x4')

# rename column Transmisie to Tractiune

df.rename(columns={'Transmisie':'Tractiune'})

,Url,Autovit Id,Pret,Oferit de,Categorie,Marca,Model,Versiune,Anul,Km,...,Capacitate baterie,Tuning,Predare leasing,Plata initiala (la predare),Valoare rata lunara,Numar de rate lunare ramase,Valoare reziduala,Contract baterie,Volan pe dreapta,Masina de epoca
0,https://www.autovit.ro/anunt/suzuki-vitara-1-6...,7049990250,16 999 EUR,Proprietar,Autoturisme,Suzuki,Vitara,1.6,2018,26 000 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autovit.ro/anunt/toyota-auris-1-8-...,7049960669,12 500 EUR,Proprietar,Autoturisme,Toyota,Auris,1.8 VVT-i Hybrid Automatik Touring Sports,2015,239 465 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autovit.ro/anunt/skoda-octavia-1-6...,7049895868,14 994 EUR,Firma,Autoturisme,Skoda,Octavia,1.6 TDI,2020,100 000 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autovit.ro/anunt/ford-focus-1-6-td...,7049990021,5 000 EUR,Proprietar,Autoturisme,Ford,Focus,1.6 TDCi DPF,2012,245 000 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autovit.ro/anunt/opel-insignia-ID7...,7049990234,17 800 EUR,Proprietar,Autoturisme,Opel,Insignia,NaN,2017,65 000 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12224,https://www.autovit.ro/anunt/citron-c4-picasso...,7049523776,6 990 EUR,Firma,Autoturisme,CitroÃ«n,C4 Picasso,2.0 HDi FAP Aut.,2012,146 000 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12225,https://www.autovit.ro/anunt/volkswagen-tiguan...,7049904550,18 189 EUR,Firma,Autoturisme,Volkswagen,Tiguan,2.0 TDI DPF DSG,2018,213 850 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12226,https://www.autovit.ro/anunt/hyundai-tucson-2-...,7049121387,17 800 EUR,Firma,Autoturisme,Hyundai,Tucson,2.0 CRDI 4WD 6MT,2016,113 842 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12227,https://www.autovit.ro/anunt/skoda-citigo-1-0-...,7049459656,6 790 EUR,Firma,Autoturisme,Skoda,Citigo,1.0 MPI,2015,132 879 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12228,https://www.autovit.ro/anunt/opel-mokka-ID7H4O...,7049459657,15 740 EUR,Firma,Autoturisme,Opel,Mokka,NaN,2017,115 723 km,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# see RON and EUR counts

df['Pret'].apply(lambda s: s[-3:]).value_counts()

EUR    11876
RON        8
Name: Pret, dtype: int64

In [9]:
# few RON => erase RON cars

df = df[df['Pret'].apply(lambda s: s[-3:]) != 'RON']

# erase EUR from prices

df['Pret'] = df['Pret'].map(lambda x: x.rstrip(' EUR'))

# rename column to include (EUR)

df = df.rename(columns={'Pret':'Pret (EUR)'})

In [10]:
# remove space from numbers

df['Pret (EUR)'] = df['Pret (EUR)'].str.replace(" ", "")
df['Pret (EUR)'] = df['Pret (EUR)'].str.replace(",", ".") # Some prices contain a comma (Romanian locale).
df['Pret (EUR)'] = df['Pret (EUR)'].astype(float)

In [11]:
# drop columns

df = df.drop(columns=['Tara de origine', 'Garantie dealer (inclusa in pret)', 'Data primei inmatriculari', 'Are VIN (Serie sasiu)', 'Numar locuri', 'Generatie', 'Optiuni culoare', 'Versiune'])

In [12]:
df.columns

Index(['Url', 'Autovit Id', 'Pret (EUR)', 'Oferit de', 'Categorie', 'Marca',
       'Model', 'Anul', 'Km', 'Combustibil', 'Putere', 'Capacitate cilindrica',
       'Norma de poluare', 'Consum Mixt', 'Cutie de viteze', 'Consum Urban',
       'Tip Caroserie', 'Numar de portiere', 'Culoare',
       'Garantie de la producator pana la', 'Fara accident in istoric',
       'Carte de service', 'Stare', 'Transmisie', 'Filtru de particule',
       'Emisii CO2', 'Se emite factura', 'Eligibil pentru finantare',
       'Inmatriculat', 'Primul proprietar (de nou)', 'Consum Extraurban',
       'sau in limita a', 'Autonomie', 'Consum mediu', 'Capacitate baterie',
       'Tuning', 'Predare leasing', 'Plata initiala (la predare)',
       'Valoare rata lunara', 'Numar de rate lunare ramase',
       'Valoare reziduala', 'Contract baterie', 'Volan pe dreapta',
       'Masina de epoca'],
      dtype='object')

In [13]:
df['Predare leasing'].isnull().sum()
#df['Tuning'].unique()

11703

In [14]:
df.columns

Index(['Url', 'Autovit Id', 'Pret (EUR)', 'Oferit de', 'Categorie', 'Marca',
       'Model', 'Anul', 'Km', 'Combustibil', 'Putere', 'Capacitate cilindrica',
       'Norma de poluare', 'Consum Mixt', 'Cutie de viteze', 'Consum Urban',
       'Tip Caroserie', 'Numar de portiere', 'Culoare',
       'Garantie de la producator pana la', 'Fara accident in istoric',
       'Carte de service', 'Stare', 'Transmisie', 'Filtru de particule',
       'Emisii CO2', 'Se emite factura', 'Eligibil pentru finantare',
       'Inmatriculat', 'Primul proprietar (de nou)', 'Consum Extraurban',
       'sau in limita a', 'Autonomie', 'Consum mediu', 'Capacitate baterie',
       'Tuning', 'Predare leasing', 'Plata initiala (la predare)',
       'Valoare rata lunara', 'Numar de rate lunare ramase',
       'Valoare reziduala', 'Contract baterie', 'Volan pe dreapta',
       'Masina de epoca'],
      dtype='object')

In [15]:
df = df.drop(['Garantie de la producator pana la', 'Stare','Emisii CO2', 'Se emite factura', 'Eligibil pentru finantare', 'sau in limita a', 'Autonomie', 'Capacitate baterie', 
                     'Tuning', 'Predare leasing', 'Plata initiala (la predare)', 'Valoare rata lunara', 'Numar de rate lunare ramase', 'Valoare reziduala', 'Contract baterie', 
                      'Volan pe dreapta', 'Masina de epoca'], axis=1)

# rename columns

df = df.rename(columns={'Transmisie':'Tractiune'})
df = df.rename(columns={'Primul proprietar (de nou)':'Primul proprietar'})

In [16]:
df['Primul proprietar'] = df['Primul proprietar'].fillna("Nu")

In [17]:
df['Primul proprietar'].unique()

array(['Nu', 'Da'], dtype=object)

In [18]:
df['Inmatriculat'] = df['Inmatriculat'].fillna("Nu")
df['Inmatriculat'].unique()

array(['Nu', 'Da'], dtype=object)

In [19]:
df.columns

Index(['Url', 'Autovit Id', 'Pret (EUR)', 'Oferit de', 'Categorie', 'Marca',
       'Model', 'Anul', 'Km', 'Combustibil', 'Putere', 'Capacitate cilindrica',
       'Norma de poluare', 'Consum Mixt', 'Cutie de viteze', 'Consum Urban',
       'Tip Caroserie', 'Numar de portiere', 'Culoare',
       'Fara accident in istoric', 'Carte de service', 'Tractiune',
       'Filtru de particule', 'Inmatriculat', 'Primul proprietar',
       'Consum Extraurban', 'Consum mediu'],
      dtype='object')

In [20]:
df['Km'].unique()

array(['26 000 km', '239 465 km', '100 000 km', ..., '113 842 km',
       '132 879 km', '115 723 km'], dtype=object)

In [21]:
df['Km'] = df['Km'].map(lambda x: x.rstrip(' km'))
df['Km'] = df['Km'].str.replace(" ", "")

In [22]:
df['Km'].unique()

array(['26000', '239465', '100000', ..., '113842', '132879', '115723'],
      dtype=object)

In [23]:
df['Combustibil']

0        Benzina
1         Hibrid
2         Diesel
3         Diesel
4         Diesel
          ...
12224     Diesel
12225     Diesel
12226     Diesel
12227    Benzina
12228     Diesel
Name: Combustibil, Length: 11876, dtype: object

In [24]:
df['Putere'].unique()

array(['120 CP', '99 CP', '115 CP', '136 CP', '330 CP', '190 CP', '75 CP',
       '140 CP', '435 CP', '612 CP', '272 CP', '252 CP', '286 CP',
       '550 CP', '110 CP', '340 CP', '204 CP', '125 CP', '143 CP',
       '218 CP', '130 CP', '381 CP', '235 CP', '150 CP', '240 CP',
       '620 CP', '224 CP', '210 CP', '258 CP', '200 CP', '177 CP',
       '90 CP', '163 CP', '92 CP', '184 CP', '122 CP', '197 CP', '105 CP',
       '60 CP', '102 CP', '170 CP', '180 CP', '625 CP', '183 CP', '65 CP',
       '500 CP', '507 CP', '440 CP', '160 CP', '231 CP', '101 CP',
       '116 CP', '194 CP', '313 CP', '103 CP', '100 CP', '215 CP',
       '68 CP', '310 CP', '85 CP', '551 CP', '129 CP', '510 CP', '182 CP',
       '155 CP', '193 CP', '320 CP', '265 CP', '185 CP', '212 CP',
       '175 CP', '106 CP', '80 CP', '95 CP', '280 CP', '77 CP', '187 CP',
       '124 CP', '23 CP', '241 CP', '305 CP', '171 CP', '73 CP', '211 CP',
       '214 CP', '245 CP', '426 CP', '165 CP', '156 CP', '109 CP',
       '266 CP', '135 CP', '146 CP', '262 CP', '639 CP', '306 CP',
       '82 CP', '164 CP', '128 CP', '112 CP', '303 CP', '333 CP',
       '522 CP', '64 CP', '88 CP', '466 CP', '173 CP', '605 CP', '300 CP',
       '107 CP', '191 CP', '205 CP', '301 CP', '149 CP', '238 CP',
       '610 CP', '67 CP', '179 CP', '450 CP', '250 CP', '354 CP',
       '585 CP', '70 CP', '275 CP', '86 CP', '259 CP', '213 CP', '50 CP',
       '132 CP', '78 CP', '195 CP', '111 CP', '198 CP', '239 CP',
       '469 CP', '256 CP', '400 CP', '290 CP', '117 CP', '468 CP',
       '232 CP', '176 CP', '188 CP', '650 CP', '66 CP', '457 CP',
       '279 CP', '600 CP', '248 CP', '575 CP', '430 CP', '91 CP',
       '174 CP', '331 CP', '157 CP', '367 CP', '152 CP', '390 CP',
       '460 CP', '181 CP', '123 CP', '249 CP', '463 CP', '230 CP',
       '560 CP', '161 CP', '145 CP', '285 CP', '147 CP', '549 CP',
       '114 CP', '449 CP', '270 CP', '118 CP', '98 CP', '404 CP',
       '580 CP', '178 CP', '233 CP', '167 CP', '345 CP', '141 CP',
       '782 CP', '299 CP', '480 CP', '72 CP', '405 CP', '571 CP',
       '422 CP', '385 CP', '192 CP', '293 CP', '395 CP', '374 CP',
       '126 CP', '220 CP', '391 CP', '263 CP', '370 CP', '292 CP',
       '158 CP', '525 CP', '416 CP', '76 CP', '420 CP', '159 CP',
       '131 CP', '84 CP', '83 CP', '284 CP', '530 CP', '54 CP', '97 CP',
       '421 CP', '344 CP', '326 CP', '55 CP', '71 CP', '820 CP', '96 CP',
       '69 CP', '94 CP', '462 CP', '251 CP', '455 CP', '402 CP', '237 CP',
       '577 CP', '225 CP', '401 CP', '394 CP', '121 CP', '557 CP',
       '350 CP', '119 CP', '41 CP', '202 CP', '74 CP', '520 CP', '142 CP',
       '489 CP', '353 CP', '380 CP', '33 CP', '410 CP', '209 CP',
       '327 CP', '360 CP', '372 CP', '339 CP', '81 CP', '629 CP',
       '319 CP', '35 CP', '166 CP', '207 CP', '260 CP', '169 CP',
       '635 CP', '669 CP', '226 CP', '144 CP', '317 CP', '1 001 CP',
       '244 CP', '153 CP', '5 CP', '139 CP', '609 CP', '640 CP', '288 CP',
       '337 CP', '341 CP', '58 CP', '670 CP', '264 CP', '87 CP', '388 CP',
       '217 CP', '349 CP', '365 CP', '476 CP', '565 CP', '532 CP',
       '236 CP', '608 CP', '138 CP', '544 CP', '151 CP', '199 CP',
       '276 CP', '584 CP', nan, '387 CP', '720 CP', '570 CP', '186 CP',
       '448 CP', '408 CP', '900 CP', '621 CP', '254 CP', '247 CP',
       '315 CP', '630 CP'], dtype=object)

In [25]:
df['Putere'] = df['Putere'].str.replace(" ", "")
df['Putere'] = df['Putere'].str.replace("CP", "")

In [26]:
df['Putere'].unique()

array(['120', '99', '115', '136', '330', '190', '75', '140', '435', '612',
       '272', '252', '286', '550', '110', '340', '204', '125', '143',
       '218', '130', '381', '235', '150', '240', '620', '224', '210',
       '258', '200', '177', '90', '163', '92', '184', '122', '197', '105',
       '60', '102', '170', '180', '625', '183', '65', '500', '507', '440',
       '160', '231', '101', '116', '194', '313', '103', '100', '215',
       '68', '310', '85', '551', '129', '510', '182', '155', '193', '320',
       '265', '185', '212', '175', '106', '80', '95', '280', '77', '187',
       '124', '23', '241', '305', '171', '73', '211', '214', '245', '426',
       '165', '156', '109', '266', '135', '146', '262', '639', '306',
       '82', '164', '128', '112', '303', '333', '522', '64', '88', '466',
       '173', '605', '300', '107', '191', '205', '301', '149', '238',
       '610', '67', '179', '450', '250', '354', '585', '70', '275', '86',
       '259', '213', '50', '132', '78', '195', '111', '198', '239', '469',
       '256', '400', '290', '117', '468', '232', '176', '188', '650',
       '66', '457', '279', '600', '248', '575', '430', '91', '174', '331',
       '157', '367', '152', '390', '460', '181', '123', '249', '463',
       '230', '560', '161', '145', '285', '147', '549', '114', '449',
       '270', '118', '98', '404', '580', '178', '233', '167', '345',
       '141', '782', '299', '480', '72', '405', '571', '422', '385',
       '192', '293', '395', '374', '126', '220', '391', '263', '370',
       '292', '158', '525', '416', '76', '420', '159', '131', '84', '83',
       '284', '530', '54', '97', '421', '344', '326', '55', '71', '820',
       '96', '69', '94', '462', '251', '455', '402', '237', '577', '225',
       '401', '394', '121', '557', '350', '119', '41', '202', '74', '520',
       '142', '489', '353', '380', '33', '410', '209', '327', '360',
       '372', '339', '81', '629', '319', '35', '166', '207', '260', '169',
       '635', '669', '226', '144', '317', '1001', '244', '153', '5',
       '139', '609', '640', '288', '337', '341', '58', '670', '264', '87',
       '388', '217', '349', '365', '476', '565', '532', '236', '608',
       '138', '544', '151', '199', '276', '584', nan, '387', '720', '570',
       '186', '448', '408', '900', '621', '254', '247', '315', '630'],
      dtype=object)

In [27]:
df = df.rename(columns={'Putere':'Putere (CP)'})

In [28]:
df['Capacitate cilindrica'].unique()

array(['1 586 cm3', '1 798 cm3', '1 598 cm3', '1 560 cm3', '2 925 cm3',
       '1 968 cm3', '1 422 cm3', '2 999 cm3', '3 982 cm3', '1 984 cm3',
       '2 967 cm3', '3 996 cm3', '1 461 cm3', '2 996 cm3', '1 986 cm3',
       '999 cm3', '1 995 cm3', '2 497 cm3', '2 993 cm3', '1 969 cm3',
       '3 855 cm3', '2 987 cm3', '2 387 cm3', '2 776 cm3', '2 400 cm3',
       '1 390 cm3', '2 199 cm3', '1 197 cm3', '2 143 cm3', '1 999 cm3',
       '1 462 cm3', '4 395 cm3', '1 686 cm3', '1 582 cm3', '1 796 cm3',
       '4 806 cm3', '3 993 cm3', '2 894 cm3', '1 896 cm3', '998 cm3',
       '2 694 cm3', '1 496 cm3', '2 171 cm3', '2 268 cm3', '1 997 cm3',
       '1 950 cm3', '3 628 cm3', '1 373 cm3', '1 870 cm3', '2 393 cm3',
       '1 399 cm3', '1 956 cm3', '5 000 cm3', '1 498 cm3', '1 596 cm3',
       '2 494 cm3', '1 998 cm3', '2 148 cm3', '2 398 cm3', '1 996 cm3',
       '2 298 cm3', '1 395 cm3', '2 191 cm3', '2 184 cm3', '1 991 cm3',
       '1 360 cm3', '1 368 cm3', '1 910 cm3', '2 597 cm3', '599 cm3',
       '898 cm3', '3 726 cm3', '2 488 cm3', '1 396 cm3', '6 162 cm3',
       '1 993 cm3', '1 753 cm3', '1 490 cm3', '2 360 cm3', '1 595 cm3',
       '1 499 cm3', '2 698 cm3', '1 242 cm3', '2 000 cm3', '1 398 cm3',
       '1 248 cm3', '1 149 cm3', '2 034 cm3', '1 333 cm3', '2 998 cm3',
       '1 339 cm3', '1 898 cm3', '2 499 cm3', '1 618 cm3', '1 332 cm3',
       '1 364 cm3', '2 188 cm3', '3 198 cm3', '1 597 cm3', '1 298 cm3',
       nan, '2 793 cm3', '5 204 cm3', '1 994 cm3', '1 256 cm3',
       '1 497 cm3', '1 198 cm3', '2 982 cm3', '2 231 cm3', '1 584 cm3',
       '2 371 cm3', '1 199 cm3', '2 995 cm3', '1 951 cm3', '2 179 cm3',
       '1 600 cm3', '1 400 cm3', '3 330 cm3', '4 367 cm3', '3 496 cm3',
       '6 126 cm3', '1 685 cm3', '1 328 cm3', '4 163 cm3', '5 547 cm3',
       '4 196 cm3', '2 487 cm3', '2 198 cm3', '2 990 cm3', '2 979 cm3',
       '2 460 cm3', '2 464 cm3', '1 580 cm3', '1 987 cm3', '1 591 cm3',
       '1 500 cm3', '1 900 cm3', '3 456 cm3', '2 688 cm3', '2 299 cm3',
       '2 300 cm3', '1 301 cm3', '2 200 cm3', '2 736 cm3', '1 495 cm3',
       '2 287 cm3', '3 995 cm3', '1 124 cm3', '3 799 cm3', '2 997 cm3',
       '2 700 cm3', '2 261 cm3', '2 477 cm3', '3 614 cm3', '1 700 cm3',
       '4 000 cm3', '1 229 cm3', '1 329 cm3', '899 cm3', '1 397 cm3',
       '6 749 cm3', '2 981 cm3', '4 462 cm3', '1 794 cm3', '4 300 cm3',
       '3 200 cm3', '6 000 cm3', '2 755 cm3', '2 495 cm3', '3 000 cm3',
       '2 746 cm3', '6 208 cm3', '1 486 cm3', '3 500 cm3', '3 600 cm3',
       '2 401 cm3', '1 295 cm3', '5 461 cm3', '1 388 cm3', '2 449 cm3',
       '1 799 cm3', '2 521 cm3', '3 498 cm3', '2 664 cm3', '1 689 cm3',
       '3 222 cm3', '2 496 cm3', '4 663 cm3', '2 926 cm3', '1 299 cm3',
       '2 151 cm3', '2 463 cm3', '5 038 cm3', '2 902 cm3', '1 589 cm3',
       '799 cm3', '6 592 cm3', '2 777 cm3', '2 157 cm3', '2 969 cm3',
       '1 587 cm3', '2 720 cm3', '1 975 cm3', '6 200 cm3', '2 831 cm3',
       '4 511 cm3', '1 300 cm3', '8 200 cm3', '3 333 cm3', '2 461 cm3',
       '4 999 cm3', '3 956 cm3', '875 cm3', '1 120 cm3', '5 980 cm3',
       '1 759 cm3', '2 435 cm3', '2 204 cm3', '400 cm3', '1 749 cm3',
       '2 893 cm3', '2 891 cm3', '2 144 cm3', '1 200 cm3', '3 901 cm3',
       '5 950 cm3', '3 902 cm3', '1 084 cm3', '3 596 cm3', '3 990 cm3',
       '2 953 cm3', '2 800 cm3', '2 685 cm3', '1 477 cm3', '523 cm3',
       '1 000 cm3', '4 973 cm3', '1 750 cm3', '2 687 cm3', '2 500 cm3',
       '1 699 cm3', '1 781 cm3', '2 498 cm3', '1 590 cm3', '3 564 cm3',
       '1 189 cm3', '1 451 cm3', '1 482 cm3', '2 402 cm3', '4 461 cm3',
       '995 cm3', '4 998 cm3', '1 349 cm3', '2 149 cm3', '3 459 cm3',
       '2 900 cm3', '996 cm3', '3 630 cm3', '5 998 cm3', '1 988 cm3',
       '3 598 cm3', '1 964 cm3', '2 480 cm3', '2 959 cm3', '2 457 cm3',
       '1 250 cm3', '1 868 cm3', '4 134 cm3', '5 654 cm3', '2 826 cm3',
       '1 086 cm3', '1 797 cm3', '1 362 cm3', '1 469 cm3', '2 977 cm3',
       '1 568 cm3', '2 068 cm3', '4 398 cm3', '2 696 cm3', '1 585 cm3',
       '3 986 cm3', '3 436 cm3', '2 986 cm3', '4 977 cm3', '4 200 cm3',
       '3 490 cm3', '3 994 cm3', '1 599 cm3', '4 499 cm3', '3 604 cm3',
       '4 164 cm3'], dtype=object)

In [29]:
df['Capacitate cilindrica'] = df['Capacitate cilindrica'].str.replace(" ", "")
df['Capacitate cilindrica'] = df['Capacitate cilindrica'].str.replace("cm3", "")
df = df.rename(columns={'Capacitate cilindrica':'Capacitate cilindrica (cm3)'})

In [30]:
df['Capacitate cilindrica (cm3)'].unique()

array(['1586', '1798', '1598', '1560', '2925', '1968', '1422', '2999',
       '3982', '1984', '2967', '3996', '1461', '2996', '1986', '999',
       '1995', '2497', '2993', '1969', '3855', '2987', '2387', '2776',
       '2400', '1390', '2199', '1197', '2143', '1999', '1462', '4395',
       '1686', '1582', '1796', '4806', '3993', '2894', '1896', '998',
       '2694', '1496', '2171', '2268', '1997', '1950', '3628', '1373',
       '1870', '2393', '1399', '1956', '5000', '1498', '1596', '2494',
       '1998', '2148', '2398', '1996', '2298', '1395', '2191', '2184',
       '1991', '1360', '1368', '1910', '2597', '599', '898', '3726',
       '2488', '1396', '6162', '1993', '1753', '1490', '2360', '1595',
       '1499', '2698', '1242', '2000', '1398', '1248', '1149', '2034',
       '1333', '2998', '1339', '1898', '2499', '1618', '1332', '1364',
       '2188', '3198', '1597', '1298', nan, '2793', '5204', '1994',
       '1256', '1497', '1198', '2982', '2231', '1584', '2371', '1199',
       '2995', '1951', '2179', '1600', '1400', '3330', '4367', '3496',
       '6126', '1685', '1328', '4163', '5547', '4196', '2487', '2198',
       '2990', '2979', '2460', '2464', '1580', '1987', '1591', '1500',
       '1900', '3456', '2688', '2299', '2300', '1301', '2200', '2736',
       '1495', '2287', '3995', '1124', '3799', '2997', '2700', '2261',
       '2477', '3614', '1700', '4000', '1229', '1329', '899', '1397',
       '6749', '2981', '4462', '1794', '4300', '3200', '6000', '2755',
       '2495', '3000', '2746', '6208', '1486', '3500', '3600', '2401',
       '1295', '5461', '1388', '2449', '1799', '2521', '3498', '2664',
       '1689', '3222', '2496', '4663', '2926', '1299', '2151', '2463',
       '5038', '2902', '1589', '799', '6592', '2777', '2157', '2969',
       '1587', '2720', '1975', '6200', '2831', '4511', '1300', '8200',
       '3333', '2461', '4999', '3956', '875', '1120', '5980', '1759',
       '2435', '2204', '400', '1749', '2893', '2891', '2144', '1200',
       '3901', '5950', '3902', '1084', '3596', '3990', '2953', '2800',
       '2685', '1477', '523', '1000', '4973', '1750', '2687', '2500',
       '1699', '1781', '2498', '1590', '3564', '1189', '1451', '1482',
       '2402', '4461', '995', '4998', '1349', '2149', '3459', '2900',
       '996', '3630', '5998', '1988', '3598', '1964', '2480', '2959',
       '2457', '1250', '1868', '4134', '5654', '2826', '1086', '1797',
       '1362', '1469', '2977', '1568', '2068', '4398', '2696', '1585',
       '3986', '3436', '2986', '4977', '4200', '3490', '3994', '1599',
       '4499', '3604', '4164'], dtype=object)

In [31]:
df['Norma de poluare'].unique()

array(['Euro 6', 'Euro 5', nan, 'Euro 4', 'Euro 3', 'Non-euro', 'Euro 2',
       'Euro 1'], dtype=object)

In [32]:
df['Norma de poluare'].isnull().sum()

3151

In [33]:
df= df.drop(['Norma de poluare'], axis = 1)

In [34]:
df.columns

Index(['Url', 'Autovit Id', 'Pret (EUR)', 'Oferit de', 'Categorie', 'Marca',
       'Model', 'Anul', 'Km', 'Combustibil', 'Putere (CP)',
       'Capacitate cilindrica (cm3)', 'Consum Mixt', 'Cutie de viteze',
       'Consum Urban', 'Tip Caroserie', 'Numar de portiere', 'Culoare',
       'Fara accident in istoric', 'Carte de service', 'Tractiune',
       'Filtru de particule', 'Inmatriculat', 'Primul proprietar',
       'Consum Extraurban', 'Consum mediu'],
      dtype='object')

In [35]:
df['Consum mediu'].isnull().sum()
df['Consum mediu'].unique()

array([nan], dtype=object)

In [36]:
nulls = df[df['Consum Mixt'].isnull()&df['Consum Urban'].isnull()&df['Consum Extraurban'].isnull()]
nulls

,Url,Autovit Id,Pret (EUR),Oferit de,Categorie,Marca,Model,Anul,Km,Combustibil,...,Numar de portiere,Culoare,Fara accident in istoric,Carte de service,Tractiune,Filtru de particule,Inmatriculat,Primul proprietar,Consum Extraurban,Consum mediu
9,https://www.autovit.ro/anunt/mercedes-benz-gle...,7048195345,115979.0,Firma,Autoturisme,Mercedes-Benz,GLE,2020,18062,Benzina,...,5.0,Negru,Da,Da,4x4,NaN,Nu,Da,NaN,NaN
10,https://www.autovit.ro/anunt/mercedes-benz-gle...,7048195375,166899.0,Firma,Autoturisme,Mercedes-Benz,GLE,2021,39904,Benzina,...,5.0,Argint,Da,Da,4x4,NaN,Nu,Da,NaN,NaN
12,https://www.autovit.ro/anunt/mercedes-benz-gle...,7048195400,104869.0,Firma,Autoturisme,Mercedes-Benz,GLE,2021,11500,Diesel,...,5.0,Albastru,Da,Da,4x4,NaN,Nu,Da,NaN,NaN
14,https://www.autovit.ro/anunt/mercedes-benz-gle...,7048197135,102589.0,Firma,Autoturisme,Mercedes-Benz,GLE,2022,8300,Diesel,...,5.0,Negru,Da,Da,4x4,NaN,Nu,Da,NaN,NaN
15,https://www.autovit.ro/anunt/audi-a7-ID7GXXY9....,7047827813,68459.0,Firma,Autoturisme,Audi,A7,2020,59533,Hibrid,...,4.0,Gri,Da,Da,4x4,NaN,Nu,Da,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12213,https://www.autovit.ro/anunt/bmw-seria-8-ID7H6...,7049900913,72566.0,Firma,Autoturisme,BMW,Seria 8,2021,22509,Diesel,...,2.0,Negru,NaN,NaN,4x4,NaN,Nu,Nu,NaN,NaN
12218,https://www.autovit.ro/anunt/bmw-seria-7-ID7H6...,7049844709,85900.0,Firma,Autoturisme,BMW,Seria 7,2021,29000,Diesel,...,NaN,Gri,Da,NaN,4x4,NaN,Nu,Nu,NaN,NaN
12219,https://www.autovit.ro/anunt/bmw-x6-ID7H6d8o.html,7049792732,82940.0,Firma,Autoturisme,BMW,X6,2021,10300,Benzina,...,NaN,Alte culori,Da,NaN,4x4,NaN,Nu,Nu,NaN,NaN
12222,https://www.autovit.ro/anunt/volkswagen-golf-p...,7049558754,7950.0,Firma,Autoturisme,Volkswagen,Golf Plus,2012,190000,Diesel,...,5.0,Gri,Da,Da,Fata,Da,Nu,Nu,NaN,NaN
12228,https://www.autovit.ro/anunt/opel-mokka-ID7H4O...,7049459657,15740.0,Firma,Autoturisme,Opel,Mokka,2017,115723,Diesel,...,5.0,Negru,Da,Da,Fata,NaN,Da,Nu,NaN,NaN

In [37]:
nulls = df[df['Consum Mixt'].isnull()&df['Consum Urban'].isnull()&df['Consum Extraurban'].isnull()]
nulls

,Url,Autovit Id,Pret (EUR),Oferit de,Categorie,Marca,Model,Anul,Km,Combustibil,...,Numar de portiere,Culoare,Fara accident in istoric,Carte de service,Tractiune,Filtru de particule,Inmatriculat,Primul proprietar,Consum Extraurban,Consum mediu
9,https://www.autovit.ro/anunt/mercedes-benz-gle...,7048195345,115979.0,Firma,Autoturisme,Mercedes-Benz,GLE,2020,18062,Benzina,...,5.0,Negru,Da,Da,4x4,NaN,Nu,Da,NaN,NaN
10,https://www.autovit.ro/anunt/mercedes-benz-gle...,7048195375,166899.0,Firma,Autoturisme,Mercedes-Benz,GLE,2021,39904,Benzina,...,5.0,Argint,Da,Da,4x4,NaN,Nu,Da,NaN,NaN
12,https://www.autovit.ro/anunt/mercedes-benz-gle...,7048195400,104869.0,Firma,Autoturisme,Mercedes-Benz,GLE,2021,11500,Diesel,...,5.0,Albastru,Da,Da,4x4,NaN,Nu,Da,NaN,NaN
14,https://www.autovit.ro/anunt/mercedes-benz-gle...,7048197135,102589.0,Firma,Autoturisme,Mercedes-Benz,GLE,2022,8300,Diesel,...,5.0,Negru,Da,Da,4x4,NaN,Nu,Da,NaN,NaN
15,https://www.autovit.ro/anunt/audi-a7-ID7GXXY9....,7047827813,68459.0,Firma,Autoturisme,Audi,A7,2020,59533,Hibrid,...,4.0,Gri,Da,Da,4x4,NaN,Nu,Da,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12213,https://www.autovit.ro/anunt/bmw-seria-8-ID7H6...,7049900913,72566.0,Firma,Autoturisme,BMW,Seria 8,2021,22509,Diesel,...,2.0,Negru,NaN,NaN,4x4,NaN,Nu,Nu,NaN,NaN
12218,https://www.autovit.ro/anunt/bmw-seria-7-ID7H6...,7049844709,85900.0,Firma,Autoturisme,BMW,Seria 7,2021,29000,Diesel,...,NaN,Gri,Da,NaN,4x4,NaN,Nu,Nu,NaN,NaN
12219,https://www.autovit.ro/anunt/bmw-x6-ID7H6d8o.html,7049792732,82940.0,Firma,Autoturisme,BMW,X6,2021,10300,Benzina,...,NaN,Alte culori,Da,NaN,4x4,NaN,Nu,Nu,NaN,NaN
12222,https://www.autovit.ro/anunt/volkswagen-golf-p...,7049558754,7950.0,Firma,Autoturisme,Volkswagen,Golf Plus,2012,190000,Diesel,...,5.0,Gri,Da,Da,Fata,Da,Nu,Nu,NaN,NaN
12228,https://www.autovit.ro/anunt/opel-mokka-ID7H4O...,7049459657,15740.0,Firma,Autoturisme,Opel,Mokka,2017,115723,Diesel,...,5.0,Negru,Da,Da,Fata,NaN,Da,Nu,NaN,NaN

In [38]:
# delete Consum mediu column
df = df.drop('Consum mediu', axis = 1)

In [39]:
df['Consum Mixt'] = df['Consum Mixt'].str.replace(",", ".")
df['Consum Mixt'] = df['Consum Mixt'].str.replace(" l/100km", "")
df['Consum Mixt'].unique()

array(['5', nan, '6', '7', '4', '7.80', '8', '9', '10', '12', '4.60', '3',
       '5.40', '65', '15', '11.90', '8.50', '2', '4.80', '6.90', '6.10',
       '52', '44', '45', '55', '2.50', '6.60', '6.40', '6.30', '7.10',
       '8.20', '6.50', '10.50', '4.50', '4.30', '11'], dtype=object)

In [40]:
df['Consum Urban'] = df['Consum Urban'].str.replace(",", ".")
df['Consum Urban'] = df['Consum Urban'].str.replace(" l/100km", "")
df['Consum Urban'].unique()

array(['6.60', '3.50', '4.70', '5.10', '8.40', '5.30', '8.90', '7.20',
       nan, '8.50', '6', '5.60', '12.30', '5.70', '8', '13.70', '8.70',
       '6.20', '12', '10.10', '4.30', '10.30', '10', '4.80', '5.90',
       '6.90', '8.80', '5.80', '7', '18.60', '6.40', '5.20', '6.80',
       '11.50', '6.10', '6.50', '9.30', '4.40', '16.20', '15.90', '5.40',
       '11.90', '4.90', '7.80', '14.50', '7.70', '6.30', '6.70', '4.50',
       '9.60', '5', '18.40', '8.30', '8.20', '11', '11.40', '3', '9.70',
       '3.80', '7.50', '4.10', '7.40', '7.30', '92', '2.80', '9.10',
       '4.20', '4', '12.90', '7.10', '5.50', '7.90', '11.60', '912.10',
       '10.60', '7.60', '9.40', '8.10', '3.70', '11.20', '9.50', '9',
       '4.60', '9.20', '15.20', '10.90', '11.30', '15.30', '19.60',
       '13.30', '9.80', '9.90', '16.80', '3.60', '10.50', '11.80', '3.90',
       '11.70', '17.80', '10.40', '15.70', '14.90', '16.10', '11.10',
       '14', '14.20', '12.60', '13.60', '10.70', '16.60', '19.80',
       '14.10', '12.80', '2.60', '13.90', '17.10', '13.80', '16.50',
       '8.60', '10.20', '14.80', '17', '10.80', '3.40', '19.40', '20',
       '16', '16.30', '13.20', '17.20', '77.80', '14.30', '14.40',
       '12.70', '3.30', '12.10', '17.50', '19.30', '12.20', '13.10',
       '3.20', '21.90', '12.40', '13.40', '14.70', '49', '15.50', '15.10',
       '15.40', '3.10', '12.50', '18.30', '19.50', '15.80', '2', '15',
       '18', '19.20', '13', '26.40', '74', '16.40', '14.60', '15.60',
       '17.40', '18.10', '17.60', '22.40', '13.50', '17.30'], dtype=object)

In [41]:
df['Consum Extraurban'] = df['Consum Extraurban'].str.replace(",", ".")
df['Consum Extraurban'] = df['Consum Extraurban'].str.replace(" l/100km", "")
df['Consum Extraurban'].unique()

array([nan, '5', '4', '7', '7.20', '6', '4.50', '8', '9', '3.90', '4.40',
       '52', '13', '9.50', '3', '6.60', '4.10', '6.20', '5.40', '5.90',
       '38', '59', '4.70', '7.90', '6.40', '5.30', '5.20', '5.60', '4.30',
       '7.40', '7.70', '3.60'], dtype=object)

In [42]:
df = df.astype({'Consum Mixt':float})
df = df.astype({'Consum Urban':float})
df = df.astype({'Consum Extraurban':float})

In [43]:
# create new column from mean of 3 Consum columns
df['Consum'] = df[['Consum Mixt', 'Consum Urban', 'Consum Extraurban']].mean(axis=1, skipna=True)
df

,Url,Autovit Id,Pret (EUR),Oferit de,Categorie,Marca,Model,Anul,Km,Combustibil,...,Numar de portiere,Culoare,Fara accident in istoric,Carte de service,Tractiune,Filtru de particule,Inmatriculat,Primul proprietar,Consum Extraurban,Consum
0,https://www.autovit.ro/anunt/suzuki-vitara-1-6...,7049990250,16999.0,Proprietar,Autoturisme,Suzuki,Vitara,2018,26000,Benzina,...,5.0,Negru,Da,Da,NaN,NaN,Nu,Nu,NaN,5.8
1,https://www.autovit.ro/anunt/toyota-auris-1-8-...,7049960669,12500.0,Proprietar,Autoturisme,Toyota,Auris,2015,239465,Hibrid,...,5.0,Gri,Da,Da,NaN,NaN,Nu,Nu,NaN,3.5
2,https://www.autovit.ro/anunt/skoda-octavia-1-6...,7049895868,14994.0,Firma,Autoturisme,Skoda,Octavia,2020,100000,Diesel,...,5.0,Albastru,Da,Da,Fata,Da,Da,Da,NaN,4.7
3,https://www.autovit.ro/anunt/ford-focus-1-6-td...,7049990021,5000.0,Proprietar,Autoturisme,Ford,Focus,2012,245000,Diesel,...,5.0,Alb,Da,Da,Fata,Da,Da,Nu,NaN,5.1
4,https://www.autovit.ro/anunt/opel-insignia-ID7...,7049990234,17800.0,Proprietar,Autoturisme,Opel,Insignia,2017,65000,Diesel,...,4.0,Alb,Da,NaN,Fata,NaN,Da,Nu,NaN,4.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12224,https://www.autovit.ro/anunt/citron-c4-picasso...,7049523776,6990.0,Firma,Autoturisme,CitroÃ«n,C4 Picasso,2012,146000,Diesel,...,5.0,Alte culori,Da,Da,Fata,NaN,Nu,Da,NaN,6.9
12225,https://www.autovit.ro/anunt/volkswagen-tiguan...,7049904550,18189.0,Firma,Autoturisme,Volkswagen,Tiguan,2018,213850,Diesel,...,5.0,Gri,NaN,NaN,Fata,Da,Nu,Da,NaN,5.7
12226,https://www.autovit.ro/anunt/hyundai-tucson-2-...,7049121387,17800.0,Firma,Autoturisme,Hyundai,Tucson,2016,113842,Diesel,...,5.0,Gri,NaN,NaN,4x4,NaN,Nu,Nu,NaN,6.0
12227,https://www.autovit.ro/anunt/skoda-citigo-1-0-...,7049459656,6790.0,Firma,Autoturisme,Skoda,Citigo,2015,132879,Benzina,...,5.0,Alb,Da,Da,Fata,NaN,Da,Nu,NaN,5.6
12228,https://www.autovit.ro/anunt/opel-mokka-ID7H4O...,7049459657,15740.0,Firma,Autoturisme,Opel,Mokka,2017,115723,Diesel,...,5.0,Negru,Da,Da,Fata,NaN,Da,Nu,NaN,NaN

In [44]:
df['Consum'].isnull().sum()

3382

In [45]:
# rename column Consum
df = df.rename(columns={'Consum':'Consum (l/100km)'})

# fill null values with mean
mean_value = df['Consum (l/100km)'].mean()
df['Consum (l/100km)'] = df['Consum (l/100km)'].fillna(value=mean_value)

In [46]:
df['Consum (l/100km)'].isnull().sum()

0

In [47]:
df.columns

Index(['Url', 'Autovit Id', 'Pret (EUR)', 'Oferit de', 'Categorie', 'Marca',
       'Model', 'Anul', 'Km', 'Combustibil', 'Putere (CP)',
       'Capacitate cilindrica (cm3)', 'Consum Mixt', 'Cutie de viteze',
       'Consum Urban', 'Tip Caroserie', 'Numar de portiere', 'Culoare',
       'Fara accident in istoric', 'Carte de service', 'Tractiune',
       'Filtru de particule', 'Inmatriculat', 'Primul proprietar',
       'Consum Extraurban', 'Consum (l/100km)'],
      dtype='object')

In [48]:
# drop columns with Consum

df = df.drop(['Consum Mixt', 'Consum Urban', 'Consum Extraurban'], axis = 1)
df.columns

Index(['Url', 'Autovit Id', 'Pret (EUR)', 'Oferit de', 'Categorie', 'Marca',
       'Model', 'Anul', 'Km', 'Combustibil', 'Putere (CP)',
       'Capacitate cilindrica (cm3)', 'Cutie de viteze', 'Tip Caroserie',
       'Numar de portiere', 'Culoare', 'Fara accident in istoric',
       'Carte de service', 'Tractiune', 'Filtru de particule', 'Inmatriculat',
       'Primul proprietar', 'Consum (l/100km)'],
      dtype='object')

In [49]:
df['Oferit de'].isnull().sum()

0

In [50]:
df['Categorie'].isnull().sum()

0

In [51]:
df['Marca'].isnull().sum()

0

In [52]:
df['Model'].isnull().sum()

0

In [53]:
df['Anul'].isnull().sum()

0

In [54]:
df['Cutie de viteze'].unique()

array(['Automata', 'Manuala'], dtype=object)

In [55]:
df['Tip Caroserie'].unique()

array(['SUV', 'Combi', 'Sedan', 'Masina de oras', 'Compacta', 'Coupe',
       'Monovolum', 'Masina mica', 'Cabrio'], dtype=object)

In [56]:
df['Numar de portiere'].unique()

array([ 5.,  4.,  2.,  3., nan,  6.])

In [57]:
df['Numar de portiere'].isnull().sum()

392

In [58]:
# set nulls to '5'
df['Numar de portiere'].dtype

dtype('float64')

In [59]:
df['Numar de portiere'] = df['Numar de portiere'].fillna(value=5)

In [60]:
df = df.astype({'Numar de portiere':'int32'})

In [61]:
df['Numar de portiere'].unique()

array([5, 4, 2, 3, 6], dtype=int32)

In [62]:
df['Culoare'].unique()

array(['Negru', 'Gri', 'Albastru', 'Alb', 'Argint', 'Maro',
       'Galben/Auriu', 'Alte culori', 'Rosu', 'Bej', 'Verde'],
      dtype=object)

In [63]:
df['Fara accident in istoric'].unique()

array(['Da', nan], dtype=object)

In [64]:
# add Nu instead of nulls

df['Fara accident in istoric'] = df['Fara accident in istoric'].fillna(value='Nu')

In [65]:
df['Carte de service'].unique()

array(['Da', nan], dtype=object)

In [66]:
# add Nu instead of nulls

df['Carte de service'] = df['Carte de service'].fillna(value='Nu')

In [67]:
df['Filtru de particule'].unique()

array([nan, 'Da'], dtype=object)

In [68]:
# add Nu instead of nulls

df['Filtru de particule'] = df['Filtru de particule'].fillna(value='Nu')

In [69]:
df['Inmatriculat'].unique()

array(['Nu', 'Da'], dtype=object)

In [70]:
display(df)

,Url,Autovit Id,Pret (EUR),Oferit de,Categorie,Marca,Model,Anul,Km,Combustibil,...,Tip Caroserie,Numar de portiere,Culoare,Fara accident in istoric,Carte de service,Tractiune,Filtru de particule,Inmatriculat,Primul proprietar,Consum (l/100km)
0,https://www.autovit.ro/anunt/suzuki-vitara-1-6...,7049990250,16999.0,Proprietar,Autoturisme,Suzuki,Vitara,2018,26000,Benzina,...,SUV,5,Negru,Da,Da,NaN,Nu,Nu,Nu,5.800000
1,https://www.autovit.ro/anunt/toyota-auris-1-8-...,7049960669,12500.0,Proprietar,Autoturisme,Toyota,Auris,2015,239465,Hibrid,...,Combi,5,Gri,Da,Da,NaN,Nu,Nu,Nu,3.500000
2,https://www.autovit.ro/anunt/skoda-octavia-1-6...,7049895868,14994.0,Firma,Autoturisme,Skoda,Octavia,2020,100000,Diesel,...,Sedan,5,Albastru,Da,Da,Fata,Da,Da,Da,4.700000
3,https://www.autovit.ro/anunt/ford-focus-1-6-td...,7049990021,5000.0,Proprietar,Autoturisme,Ford,Focus,2012,245000,Diesel,...,Combi,5,Alb,Da,Da,Fata,Da,Da,Nu,5.100000
4,https://www.autovit.ro/anunt/opel-insignia-ID7...,7049990234,17800.0,Proprietar,Autoturisme,Opel,Insignia,2017,65000,Diesel,...,Sedan,4,Alb,Da,Nu,Fata,Nu,Da,Nu,4.700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12224,https://www.autovit.ro/anunt/citron-c4-picasso...,7049523776,6990.0,Firma,Autoturisme,CitroÃ«n,C4 Picasso,2012,146000,Diesel,...,Monovolum,5,Alte culori,Da,Da,Fata,Nu,Nu,Da,6.900000
12225,https://www.autovit.ro/anunt/volkswagen-tiguan...,7049904550,18189.0,Firma,Autoturisme,Volkswagen,Tiguan,2018,213850,Diesel,...,SUV,5,Gri,Nu,Nu,Fata,Da,Nu,Da,5.700000
12226,https://www.autovit.ro/anunt/hyundai-tucson-2-...,7049121387,17800.0,Firma,Autoturisme,Hyundai,Tucson,2016,113842,Diesel,...,SUV,5,Gri,Nu,Nu,4x4,Nu,Nu,Nu,6.000000
12227,https://www.autovit.ro/anunt/skoda-citigo-1-0-...,7049459656,6790.0,Firma,Autoturisme,Skoda,Citigo,2015,132879,Benzina,...,Masina mica,5,Alb,Da,Da,Fata,Nu,Da,Nu,5.600000
12228,https://www.autovit.ro/anunt/opel-mokka-ID7H4O...,7049459657,15740.0,Firma,Autoturisme,Opel,Mokka,2017,115723,Diesel,...,SUV,5,Negru,Da,Da,Fata,Nu,Da,Nu,6.853901

In [71]:
df.isnull().sum()

Url                               0
Autovit Id                        0
Pret (EUR)                        0
Oferit de                         0
Categorie                         0
Marca                             0
Model                             0
Anul                              0
Km                                0
Combustibil                       0
Putere (CP)                       1
Capacitate cilindrica (cm3)       6
Cutie de viteze                   0
Tip Caroserie                     0
Numar de portiere                 0
Culoare                           0
Fara accident in istoric          0
Carte de service                  0
Tractiune                      1934
Filtru de particule               0
Inmatriculat                      0
Primul proprietar                 0
Consum (l/100km)                  0
dtype: int64

In [72]:
# fill null values with mean
mean_value = df['Putere (CP)'].astype(float).mean()
df['Putere (CP)'] = df['Putere (CP)'].fillna(value=mean_value)

mean_value = df['Capacitate cilindrica (cm3)'].astype(float).mean()
df['Capacitate cilindrica (cm3)'] = df['Capacitate cilindrica (cm3)'].fillna(value=mean_value)

In [73]:
df['Putere (CP)']

0        120
1         99
2        115
3        115
4        136
        ...
12224    163
12225    150
12226    136
12227     60
12228    136
Name: Putere (CP), Length: 11876, dtype: object

In [74]:
df = df.astype({'Putere (CP)':'float'})

In [75]:
df = df.astype({'Capacitate cilindrica (cm3)':'float'})

In [76]:
df.dtypes

Url                             object
Autovit Id                       int64
Pret (EUR)                     float64
Oferit de                       object
Categorie                       object
Marca                           object
Model                           object
Anul                             int64
Km                              object
Combustibil                     object
Putere (CP)                    float64
Capacitate cilindrica (cm3)    float64
Cutie de viteze                 object
Tip Caroserie                   object
Numar de portiere                int32
Culoare                         object
Fara accident in istoric        object
Carte de service                object
Tractiune                       object
Filtru de particule             object
Inmatriculat                    object
Primul proprietar               object
Consum (l/100km)               float64
dtype: object

In [77]:
df.isnull().sum()

Url                               0
Autovit Id                        0
Pret (EUR)                        0
Oferit de                         0
Categorie                         0
Marca                             0
Model                             0
Anul                              0
Km                                0
Combustibil                       0
Putere (CP)                       0
Capacitate cilindrica (cm3)       0
Cutie de viteze                   0
Tip Caroserie                     0
Numar de portiere                 0
Culoare                           0
Fara accident in istoric          0
Carte de service                  0
Tractiune                      1934
Filtru de particule               0
Inmatriculat                      0
Primul proprietar                 0
Consum (l/100km)                  0
dtype: int64

In [78]:
df['Tractiune'].value_counts()

Fata     4731
4x4      4467
Spate     744
Name: Tractiune, dtype: int64

In [79]:
df['Tractiune'] = df['Tractiune'].fillna(value="Nu e mentionat")

In [80]:
# Transform Yes/No columns into boolean columns.

BOOL_COLS = ["Inmatriculat", "Fara accident in istoric", "Carte de service", "Filtru de particule", "Primul proprietar"]
display("Before conversion", df[BOOL_COLS].apply(lambda col: col.value_counts()))

df[BOOL_COLS] = df[BOOL_COLS].replace({"Da": True, "Nu": False})
display("After conversion", df[BOOL_COLS].apply(lambda col: col.value_counts()))

'Before conversion'

,Inmatriculat,Fara accident in istoric,Carte de service,Filtru de particule,Primul proprietar
Da,5108,6966,7531,4364,5164
Nu,6768,4910,4345,7512,6712

'After conversion'

,Inmatriculat,Fara accident in istoric,Carte de service,Filtru de particule,Primul proprietar
False,6768,4910,4345,7512,6712
True,5108,6966,7531,4364,5164

In [81]:
df.isnull().sum()

Url                            0
Autovit Id                     0
Pret (EUR)                     0
Oferit de                      0
Categorie                      0
Marca                          0
Model                          0
Anul                           0
Km                             0
Combustibil                    0
Putere (CP)                    0
Capacitate cilindrica (cm3)    0
Cutie de viteze                0
Tip Caroserie                  0
Numar de portiere              0
Culoare                        0
Fara accident in istoric       0
Carte de service               0
Tractiune                      0
Filtru de particule            0
Inmatriculat                   0
Primul proprietar              0
Consum (l/100km)               0
dtype: int64

In [82]:
df.to_csv(OUTPUT_PATH)